language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master

install:
  - npm --prefix /$PROJECT_NAME install

before_script:
  - npm install -g firebase-tools
  
script:
  - echo "Deployment started"

deploy:
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN
