language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - echo "Starting Functions Deployment"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
