language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master

install:
  - npm --prefix /functions install

before_script:
  - npm npm --prefix /

script:
  - echo "Deployment started"

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
