language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master
    
script: echo "Firebase Functions Deployment" 

deploy:
  provider: firebase
  token:
    secure: "MLGOP9RqYXWur/sq5Qvrfr4+wZLhOW5Gzmi1XihVQmVTq/1auAQzIaszcsgl8gNCqc/Rlpiw8yteoOYh8hkF1ddijWhwvCqpQNGPxagDfKxPkCyFrYnwpHWXO/QYmOI8CpAIWefNCdB2IUhx/9A69wgOHB5gQoPm/UcNRYTTcm3sXC1UTfxNlbDn518TEdFck+Fr2NZpgb82enPQtsMuR0yf3BiorjjXIqKnWNF0aTKerOaWpIX6mpL3XSEakDwMy+PAxp9g6XL/mFkowN1kDmgd5rHlCcSHKoUN5bLhwJIwKtir9xovahbjl/CXybnlylL8vBxSx1LACYYWglRpyYTpxyt5PUe81oD/YIuoFoYTZRfG1oTToffV6Mk0AqUjuDBJ5qPljureXUex7ufRV9kPDBwycSrgaCvA51E/+x1lBbZFM4vD91ScnBcHvfHiiC7mFkiOVBNBLaIiRLCGaOR+6Cm4oMZbMA5AhyQq5qm1eubEszyKsFbIakViDAJ3Xb25NBMR18aNn1DlYm0X8nYtbeA7zLlxEoaZAipFYaFRMkUrwnnxTejNI3LG4PduZ+ewNKjaIlZ8PGfF4QJX5Sw5y7zK4eBsmc/4YVUQg9c052yOD2Zk1FXm+RofnnZNyYiGUscdsZBinfG0mWsVrTDj1FB/5FgvyFfr5OSihY0="
  project: "leanontree-5358a" 
