language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - cd functions

script:
  - npm install

deploy:
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN
