language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master
    
script: echo "Firebase Functions Deployment" 

deploy:
  provider: firebase
  token:
    secure: "$ENCRYPTED_TOKEN"
  project: "LeanOnTree" 
