language: node_js
node_js:
- 6.14.0
branches:
  only:
  - master
script: echo "Firebase Functions Deployment"
deploy:
  provider: firebase
  token:
    secure: J+zyyvCCpqlZiu/dfmpJ7cQyeWpWA7qxwzSylJKO3eTb2Dr7G8yiyyPFkkSWhtJ7C97qtELDHqo35i6+l7SiWSH2bEgJKcAvotIJ1NQu4mWqBfYvfOJsfkbnvaNNuumlDIuqFQEQ1HaQ1/An9ts6P3yhTRZ6tNc3r/tbnj2YIhHgm/dQBRZ+8riIj6+psuwr03JncMV0UgpIgfFJ3/UL+50UXvqGtr56dXzx3osMr+JwHUT/mDabsxpl4F7a8TDPYypTf6F/mKTPVNm/UuYmZ42eeSkfrE4xtYTf3eTFQaR7VKUaOxnDu6tt9FDlNUtbOrHJf0BOI0905tqYsrOQlTJuPtCIxhoTmg1KRksaFP2N984Jxjwnj39NVnKfTMslnZGdiBnKEu+bSO+NUwJjZFdgg1VcOTC8/qoSgihQ/DMycn2UTX74OHSknflYOQpJB4a7yqQTYddYGmoDTkaWMNED4h36ghMGKeNuuIS10WeGa/VYc7pP2LAjlJXJa0XoOWFoBMAwn08N3PvM1mCsNzLuEUohXMMXoMum5yrY3Ad2lQCXVHoftRY6von/gefEKxsns65olvLJE8Auirn5EDjrigDYEu0k1Ct24LDXs/kO6GY4dYl0I3u90o9R0tZL6/B5+/jS3RYnzRjJYkQsKozdQYc1GC2f0djrKKUwhaU=
  project: leanontree-5358a    

