language: node_js
node_js:
  - "6.14.0"

branches:
  only:
    - master

install:
  - npm --prefix /$PROJECT_NAME install

before_script:
  - npm npm --prefix /

script:
  - functions\npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
